# http://blog.tgrrtt.com/exploring-the-travisci-configuration-file
# Todo: Don't forget to update iOS, tvOS and watchOS schemes for testing once tests are available.

language: objective-c
osx_image: xcode10.1
cache: cocoapods
before_install:
  - gem install cocoapods # Since Travis is not always on latest version…
script:
  - set -o pipefail
  - travis_retry swift test
  - travis_retry xcodebuild -workspace "Metron.xcworkspace" -scheme "Demo" build CODE_SIGN_IDENTITY="" | xcpretty
  - travis_retry xcodebuild -workspace "Metron.xcworkspace" -scheme "Metron-iOS" build | xcpretty
  - travis_retry xcodebuild -workspace "Metron.xcworkspace" -scheme "Metron-macOS" build-for-testing test | xcpretty
  - travis_retry xcodebuild -workspace "Metron.xcworkspace" -scheme "Metron-tvOS" build | xcpretty
  - travis_retry xcodebuild -workspace "Metron.xcworkspace" -scheme "Metron-watchOS" build | xcpretty
  - pod lib lint
